import { AppShell } from "@mantine/core";
import Head from "next/head";
import { type ReactElement } from "react";
import { PlannerHeader } from "./PlannerHeader/PlannerHeader";
import { PlannerNavbar } from "./PlannerNavbar/PlannerNavbar";

const Layout = ({ children }: { children: ReactElement }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        navbar={<PlannerNavbar />}
        header={<PlannerHeader />}
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        {children}
      </AppShell>
    </>
  );
};

export default Layout;
